// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Two_field_errors', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Two_field_errors', async function() {
    await driver.get("http://localhost:8080/")
    await driver.manage().window().setRect({ width: 1920, height: 1080 })
    await driver.findElement(By.css("input:nth-child(2)")).click()
    await driver.findElement(By.css("input:nth-child(2)")).sendKeys("Adriano")
    await driver.findElement(By.css("input:nth-child(4)")).sendKeys("Pedro")
    await driver.findElement(By.css("input:nth-child(6)")).sendKeys("p@p")
    await driver.findElement(By.css(".submit")).click()
  })
})
